#!/usr/bin/env python3.10
import os
import sys
# import pyperclip
from getpass import getpass

from time import sleep


__version__ = '0.4 beta'

from src.console import Console

title = fr"""

         Password Storage
  _____   __          __   _____ 
 |  __ \  \ \        / /  / ____|
 | |__) |  \ \  /\  / /  | (___  
 |  ___/    \ \/  \/ /    \___ \ 
 | |         \  /\  /     ____) |
 |_|          \/  \/     |_____/   by TheK4n

Github  : https://github.com/TheK4n
Version : {__version__}

"""


class MyError(Exception):
    pass


def main():

    console = Console(getpass(prompt="[?] Master password: "))
    if console.master.check():
        console.loop()
    else:
        print("\n[X] Wrong password", file=sys.stderr)
        sleep(5)
        exit(1)


if __name__ == '__main__':
    try:
        main()
    except EOFError:
        print('\n[X] PWS stopped', file=sys.stderr)
        exit(1)
    except KeyboardInterrupt:
        print('\n[X] PWS stopped', file=sys.stderr)
        exit(130)
    finally:
        os.system(["cls", "clear"][os.name == 'posix'])
